services:
  - type: web
    name: knit-cse-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn knit_cse_backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1"
      - key: CORS_ALLOWED_ORIGINS
        value: "http://localhost:5173"
