# Generated by Django 6.0.2 on 2026-03-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('degree', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('intake', models.CharField(max_length=100)),
                ('curriculum', models.TextField(blank=True)),
                ('fees', models.CharField(blank=True, default='As per government norms', max_length=200)),
                ('eligibility', models.JSONField(default=list)),
                ('highlights', models.JSONField(default=list)),
                ('career_prospects', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('image', models.ImageField(blank=True, null=True, upload_to='featured/')),
                ('file_size', models.CharField(blank=True, default='', max_length=30)),
                ('language', models.CharField(blank=True, default='English', max_length=30)),
                ('date', models.CharField(blank=True, default='', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('href', models.CharField(default='/', max_length=500)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='quicklinks/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
