# Generated by Django 6.0.2 on 2026-03-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_circular_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='circular',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='circulars/'),
        ),
        migrations.AddField(
            model_name='notice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notices/'),
        ),
    ]
