# Generated by Django 6.0.2 on 2026-03-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_circular_file_notice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryevent',
            name='location',
            field=models.CharField(default='KNIT Campus', max_length=200),
        ),
    ]
