# Generated by Django 6.0.2 on 2026-03-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_galleryevent_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text_1', models.TextField(blank=True, default='The Department of Computer Science & Engineering was established in 2010 with an intake of 60 students. The department has highly qualified, committed and well experienced faculty members with varied specializations. The faculties are involved in organizing and participating in several seminars, conferences and workshops. They have also published research papers in various national and international journals, presented papers in conferences in India. Over the years, the department has become a center of excellence, providing in-depth technical knowledge and opportunities for innovation and research, with well-equipped computer facilities.')),
                ('intro_text_2', models.TextField(blank=True, default='Computer Science & Engineering Department is the first point of contact for the campus community by supporting telephone, computing, networking, and applications. CSE Department is dedicated to facilitate and enhance teaching, learning, and administrative services and to increase the productivity and efficiency using information technology resources.')),
                ('objective', models.TextField(blank=True, default='To be center of excellence in technical higher education, research, and support services, capable of making significant contribution to individual and societal empowerment.')),
                ('vision', models.TextField(blank=True, default='To be centre of excellence in the computer science & engineering which will produce globally competent engineers with the moral values and technical skills for the betterment of the society.')),
                ('mission', models.TextField(blank=True, default='• To groom our students with the quality of leadership and communication skills by working on real life projects.\n• To create an environment for engineering knowledge and innovative research.')),
            ],
            options={
                'verbose_name': 'About Department',
            },
        ),
        migrations.CreateModel(
            name='AboutSidebarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('href', models.CharField(default='/', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
