# Generated by Django 6.0.2 on 2026-03-23 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_aboutdepartment_aboutsidebarlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('department', models.CharField(default='CSE', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/photos/')),
                ('profile_link', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('enrollment_no', models.CharField(max_length=100)),
                ('batch', models.CharField(help_text='e.g. 2021-2025', max_length=50)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='content.course')),
            ],
            options={
                'verbose_name_plural': 'Students',
                'ordering': ['-course', '-batch', 'name'],
            },
        ),
    ]
