# Generated by Django 6.0.2 on 2026-03-23 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_staff_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentListPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_year', models.CharField(help_text='e.g., 2024-2025', max_length=20)),
                ('year_of_study', models.CharField(help_text='e.g., 1st Year', max_length=20)),
                ('file', models.FileField(upload_to='student_lists/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_lists', to='content.course')),
            ],
            options={
                'verbose_name_plural': 'Student List PDFs',
                'ordering': ['-session_year', 'year_of_study'],
            },
        ),
    ]
