# Generated by Django 6.0.2 on 2026-03-28 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_studentlistpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='e.g., Year 1', max_length=20)),
                ('file', models.FileField(upload_to='courses/syllabuses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabuses', to='content.course')),
            ],
            options={
                'verbose_name_plural': 'Course Syllabuses',
                'ordering': ['course', 'year'],
            },
        ),
        migrations.CreateModel(
            name='CourseTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='e.g., Year 1', max_length=20)),
                ('file', models.FileField(upload_to='courses/timetables/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='content.course')),
            ],
            options={
                'verbose_name_plural': 'Course Timetables',
                'ordering': ['course', 'year'],
            },
        ),
    ]
