# Generated by Django 6.0.2 on 2026-03-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_coursesyllabus_coursetimetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='courses/brochures/'),
        ),
    ]
