# Generated by Django 6.0.2 on 2026-04-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_course_brochure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Contact Us', max_length=200)),
                ('page_subtitle', models.TextField(default="We're here to help and answer any questions you might have about the Computer Science & Engineering department.")),
                ('address_line_1', models.CharField(default='Kamla Nehru Institute of Technology,', max_length=300)),
                ('address_line_2', models.CharField(default='Sultanpur, Uttar Pradesh - 228118,', max_length=300)),
                ('address_line_3', models.CharField(default='India', max_length=300)),
                ('phone', models.CharField(default='+91-5362-240454', max_length=100)),
                ('email', models.CharField(default='cse@knit.ac.in', max_length=200)),
                ('map_embed_url', models.URLField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d14309.832717983633!2d82.07223635541991!3d26.2792611!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x399a7c86d691219f%3A0x99a3eb1e7c07f78f!2sKamla%20Nehru%20Institute%20of%20Technology%2C%20Sultanpur%20(U.P.)!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', max_length=1000)),
            ],
            options={
                'verbose_name': 'Contact Info',
            },
        ),
        migrations.CreateModel(
            name='DirectoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('mobile', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Directory Entries',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
