# Generated by Django 6.0.2 on 2026-04-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_contactinfo_directoryentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/banners/')),
                ('caption', models.CharField(blank=True, default='', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
